# Configuration constants
TRAIN_JSON_URL = "https://raw.githubusercontent.com/teacherpeterpan/Logic-LLM/refs/heads/main/data/LogicalDeduction/train.json"
TRAIN_JSON_FILE = "train.json"
DEV_JSON_URL = "https://raw.githubusercontent.com/teacherpeterpan/Logic-LLM/refs/heads/main/data/LogicalDeduction/dev.json"
DEV_JSON_FILE = "test.json"

SYSTEM_PROMPT = """
Respond in the following format:
<reasoning>
...
</reasoning>
<answer>
...
</answer>
"""

# Prompt templates for different solving approaches
PROLOG_PROMPT = [
    {"role": "system", "content": "You are a Prolog program generator. Given a logical deduction problem with a context and multiple choice options, generate a Prolog program that solves the problem. Keep the order consistent (e.g., leftmost, newest, and first to arrive objects must be at the beginning of the Solution list, while rightmost, oldest and last to arrive should be at the end). Avoid errors by, for example, using 'Pos is Len-1' and 'nth1(Pos, S, X)' when an object X is said to be second from the right, or second oldest. Follow closely the format of the following few-shot examples to solve the problem at the end in the same way. Generate the solution as a valid Prolog program starting with `solve(Answer) :-` and having the program enclosed in triple backticks labeled `prolog`."},
    
    {"role": "user", "content": "Q: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph.\n\nIn a golf tournament, there were three golfers: Mel, Ada, and Ana. Mel finished last. Ana finished second.\nOptions:\nA) Mel finished second.\nB) Ada finished second.\nC) Ana finished second."},
    {"role": "assistant", "content": "```prolog\nsolve(Answer):-\n    Solution = [_,_,_], % The solution list contains set of three objects arranged in a fixed order\n    member(mel,Solution), % 'mel' is a member of the ordered list\n    member(ada,Solution), % 'ada' is a member of the ordered list\n    member(ana,Solution), % 'ana' is a member of the ordered list\n    clue1(Solution), % Use clue 1 to get solution\n    clue2(Solution), % Use clue 2 to get solution\n    choose_option(Solution,Answer). % Choose the correct option\n\nclue1(S):- length(S,Len), nth1(Len,S,mel). % 'Mel finished last'\nclue2(S):- nth1(2,S,ana). % 'Ana finished second'\n\nchoose_option(S,a):- nth1(2,S,mel). % 'A) Mel finished second'\nchoose_option(S,b):- nth1(2,S,ada). % 'B) Ada finished second'\nchoose_option(S,c):- nth1(2,S,ana). % 'C) Ana finished second'```"},
    
    {"role": "user", "content": "Q: The following paragraphs each describe a set of five objects arranged in a fixed order. The statements are logically consistent within each paragraph.\n\nOn a shelf, there are five books: a green book, a blue book, a white book, a purple book, and a yellow book. The blue book is to the right of the yellow book. The white book is to the left of the yellow book. The blue book is the second from the right. The purple book is the second from the left.\nOptions:\nA) The green book is the second from the left.\nB) The blue book is the second from the left.\nC) The white book is the second from the left.\nD) The purple book is the second from the left.\nE) The yellow book is the second from the left."},
    {"role": "assistant", "content": "```prolog\nsolve(Answer):-\n    Solution = [_,_,_,_,_], % The solution list contains set of five objects arranged in a fixed order\n    member(green,Solution), % 'green' is a member of the ordered list\n    member(blue,Solution), % 'blue' is a member of the ordered list\n    member(white,Solution), % 'white' is a member of the ordered list\n    member(purple,Solution), % 'purple' is a member of the ordered list\n    member(yellow,Solution), % 'yellow' is a member of the ordered list\n    clue1(Solution), % Use clue 1 to get solution\n    clue2(Solution), % Use clue 2 to get solution\n    clue3(Solution), % Use clue 3 to get solution\n    clue4(Solution), % Use clue 4 to get solution\n    choose_option(Solution,Answer). % Choose the correct option\n\nclue1(S):- nth1(X,S,blue), nth1(Y,S,yellow), X > Y. % 'The blue book is to the right of the yellow book'\nclue2(S):- nth1(X,S,white), nth1(Y,S,yellow), X < Y. % 'The white book is to the left of the yellow book'\nclue3(S):- length(S,Len), Pos is Len-1, nth1(Pos,S,blue). % 'The blue book is the second from the right'\nclue4(S):- nth1(2,S,purple). % 'The purple book is the second from the left'\n\nchoose_option(S,a):- nth1(2,S,green). % 'A) The green book is the second from the left'\nchoose_option(S,b):- nth1(2,S,blue). % 'B) The blue book is the second from the left'\nchoose_option(S,c):- nth1(2,S,white). % 'C) The white book is the second from the left'\nchoose_option(S,d):- nth1(2,S,purple). % 'D) The purple book is the second from the left'\nchoose_option(S,e):- nth1(2,S,yellow). % 'E) The yellow book is the second from the left'```"},
    
    {"role": "user", "content": "Q: The following paragraphs each describe a set of seven objects arranged in a fixed order. The statements are logically consistent within each paragraph.\n\nA fruit stand sells seven fruits: loquats, peaches, watermelons, plums, kiwis, mangoes, and pears. The pears are more expensive than the kiwis. The watermelons are less expensive than the peaches. The mangoes are the third-cheapest. The watermelons are the third-most expensive. The plums are the second-most expensive. The loquats are the second-cheapest.\nOptions:\nA) The loquats are the third-most expensive.\nB) The peaches are the third-most expensive.\nC) The watermelons are the third-most expensive.\nD) The plums are the third-most expensive.\nE) The kiwis are the third-most expensive.\nF) The mangoes are the third-most expensive.\nG) The pears are the third-most expensive."},
    {"role": "assistant", "content": "\n````prolog\nsolve(Answer):-\n    Solution = [_,_,_,_,_,_,_], % The solution list contains set of seven objects arranged in a fixed order\n    member(loquats,Solution), % 'loquats' is a member of the ordered list\n    member(peaches,Solution), % 'peaches' is a member of the ordered list\n    member(watermelons,Solution), % 'watermelons' is a member of the ordered list\n    member(plums,Solution), % 'plums' is a member of the ordered list\n    member(kiwis,Solution), % 'kiwis' is a member of the ordered list\n    member(mangoes,Solution), % 'mangoes' is a member of the ordered list\n    member(pears,Solution), % 'pears' is a member of the ordered list\n    clue1(Solution), % Use clue 1 to get solution\n    clue2(Solution), % Use clue 2 to get solution\n    clue3(Solution), % Use clue 3 to get solution\n    clue4(Solution), % Use clue 4 to get solution\n    clue5(Solution), % Use clue 5 to get solution\n    clue6(Solution), % Use clue 6 to get solution\n    choose_option(Solution,Answer). % Choose the correct option\n\nclue1(S):- nth1(X,S,pears), nth1(Y,S,kiwis), X > Y. % 'The pears are more expensive than the kiwis'\nclue2(S):- nth1(X,S,watermelons), nth1(Y,S,peaches), X < Y. % 'The watermelons are less expensive than the peaches'\nclue3(S):- nth1(3,S,mangoes). % 'The mangoes are the third-cheapest'\nclue4(S):- length(S,Len), Pos is Len-2, nth1(Pos,S,watermelons). % 'The watermelons are the third-most expensive'\nclue5(S):- length(S,Len), Pos is Len-1, nth1(Pos,S,plums). % 'The plums are the second-most expensive'\nclue6(S):- nth1(2,S,loquats). % 'The loquats are the second-cheapest'\n\nchoose_option(S,a):- length(S,Len), Pos is Len-2, nth1(Pos,S,loquats). % 'A) The loquats are the third-most expensive'\nchoose_option(S,b):- length(S,Len), Pos is Len-2, nth1(Pos,S,peaches). % 'B) The peaches are the third-most expensive'\nchoose_option(S,c):- length(S,Len), Pos is Len-2, nth1(Pos,S,watermelons). % 'C) The watermelons are the third-most expensive'\nchoose_option(S,d):- length(S,Len), Pos is Len-2, nth1(Pos,S,plums). % 'D) The plums are the third-most expensive'\nchoose_option(S,e):- length(S,Len), Pos is Len-2, nth1(Pos,S,kiwis). % 'E) The kiwis are the third-most expensive'\nchoose_option(S,f):- length(S,Len), Pos is Len-2, nth1(Pos,S,mangoes). % 'F) The mangoes are the third-most expensive'\nchoose_option(S,g):- length(S,Len), Pos is Len-2, nth1(Pos,S,pears). % 'G) The pears are the third-most expensive'```"}
]

PROLOG_PROMPT_1 = [
    {"role": "system", "content": "You are a Prolog program generator. Given a logical deduction problem with a context and multiple choice options, generate a Prolog program that solves the problem. Keep the order consistent (e.g., leftmost, newest, and first to arrive objects must be at the beginning of the Solution list, while rightmost, oldest and last to arrive should be at the end). Avoid errors by, for example, using 'Pos is Len-1' and 'nth1(Pos, S, X)' when an object X is said to be second from the right, or second oldest. Follow closely the format of the following example to solve the problem at the end in the same way. Generate the solution as a valid Prolog program starting with `solve(Answer) :-` and having the program enclosed in triple backticks labeled `prolog`."},
    
    {"role": "user", "content": "Q: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph.\n\nIn a golf tournament, there were three golfers: Mel, Ada, and Ana. Mel finished last. Ana finished second.\nOptions:\nA) Mel finished second.\nB) Ada finished second.\nC) Ana finished second."},
    {"role": "assistant", "content": "```prolog\nsolve(Answer):-\n    Solution = [_,_,_], % The solution list contains set of three objects arranged in a fixed order\n    member(mel,Solution), % 'mel' is a member of the ordered list\n    member(ada,Solution), % 'ada' is a member of the ordered list\n    member(ana,Solution), % 'ana' is a member of the ordered list\n    clue1(Solution), % Use clue 1 to get solution\n    clue2(Solution), % Use clue 2 to get solution\n    choose_option(Solution,Answer). % Choose the correct option\n\nclue1(S):- length(S,Len), nth1(Len,S,mel). % 'Mel finished last'\nclue2(S):- nth1(2,S,ana). % 'Ana finished second'\n\nchoose_option(S,a):- nth1(2,S,mel). % 'A) Mel finished second'\nchoose_option(S,b):- nth1(2,S,ada). % 'B) Ada finished second'\nchoose_option(S,c):- nth1(2,S,ana). % 'C) Ana finished second'```"},
]

PROLOG_PROMPT_NO_FEW_SHOT = [
    {"role": "system", "content": "You are a Prolog program generator. Given a logical deduction problem, generate a Prolog program that is able to solve it. It is important that you adhere to a specific format when creating the Prolog program: start with a 'solve(Answer)' predicate in which Answer must unify with a letter corresponding to the correct answer to the problem; include as many 'clueX(S)' as necessary with X being an identifying number; and, finally add as many 'choose_option(S,Letter)' as necessary, where S is the list with the ordered objects passed to the function and Letter is a character corresponding to each letter option. Keep the order consistent (e.g., leftmost, newest, and first to arrive objects must be at the beginning of the Solution list, while rightmost, oldest and last to arrive should be at the end). Avoid errors by, for example, using 'Pos is Len-1' and 'nth1(Pos, S, X)' when an object X is said to be second from the right, or second oldest. Now, given the problem below, generate a Prolog program that solves it.Generate the solution as a valid Prolog program starting with `solve(Answer) :-` and enclosed in triple backticks labeled `prolog`"},
]

COT_PROMPT = [
    {"role": "system", "content": f"You are a logical deduction assistant. {SYSTEM_PROMPT}"},
    {"role": "user", "content": "Q: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph.\n\nIn a golf tournament, there were three golfers: Mel, Ada, and Ana. Mel finished last. Ana finished second.\nOptions:\nA) Mel finished second.\nB) Ada finished second.\nC) Ana finished second.\nThink step by step to solve this problem. After your reasoning, state your final answer in the format 'Answer: [letter]' on a new line."},
    {"role": "assistant", "content": "<reasoning>Let's think step by step.\n\n(1) Mel finished last: \"(above) ? ? Mel (below)\".\n(2) Ana finished second: \"(above) ? Ana Mel (below)\".\n(3) Combining (1) and (2) we get the following ordering: \"(above) Ada Ana Mel (below)\".\nAccording to this ordering, the person who finished second is Ana.\nAna finished second.</reasoning> <answer>Answer: C</answer>"},
    
    {"role": "user", "content": "Q: The following paragraphs each describe a set of five objects arranged in a fixed order. The statements are logically consistent within each paragraph.\n\nOn a shelf, there are five books: a green book, a blue book, a white book, a purple book, and a yellow book. The blue book is to the right of the yellow book. The white book is to the left of the yellow book. The blue book is the second from the right. The purple book is the second from the left.\nOptions:\nA) The green book is the second from the left.\nB) The blue book is the second from the left.\nC) The white book is the second from the left.\nD) The purple book is the second from the left.\nE) The yellow book is the second from the left.\nThink step by step to solve this problem. After your reasoning, state your final answer in the format 'Answer: [letter]' on a new line."},
    {"role": "assistant", "content": "<reasoning>Let's think step by step.\n(1) The blue book is to the right of the yellow book: \"(left) ? yellow ? blue ? (right)\".\n(2) The white book is to the left of the yellow book: \"(left) ? white ? yellow ? (right)\".\n(3) The blue book is the second from the right: \"(left) ? ? ? blue ? (right)\".\n(4) The purple book is the second from the left: \"(left) ? purple ? ? ? (right)\".\n(5) Combining (3) and (4) we get the following ordering: \"(left) ? purple ? blue ? (right)\".\n(6) Combining (1), (2), and (5) we get the following ordering: \"(left) white purple yellow blue green (right)\".\nAccording to this ordering, the second from the left is the purple book.\nThe purple book is the second from the left. </reasoning> <answer> Answer: D </answer>"},
    
    {"role": "user", "content": "Q: The following paragraphs each describe a set of seven objects arranged in a fixed order. The statements are logically consistent within each paragraph.\n\nA fruit stand sells seven fruits: loquats, peaches, watermelons, plums, kiwis, mangoes, and pears. The pears are more expensive than the kiwis. The watermelons are less expensive than the peaches. The mangoes are the third-cheapest. The watermelons are the third-most expensive. The plums are the second-most expensive. The loquats are the second-cheapest.\nOptions:\nA) The loquats are the third-most expensive.\nB) The peaches are the third-most expensive.\nC) The watermelons are the third-most expensive.\nD) The plums are the third-most expensive.\nE) The kiwis are the third-most expensive.\nF) The mangoes are the third-most expensive.\nG) The pears are the third-most expensive.\nThink step by step to solve this problem. After your reasoning, state your final answer in the format 'Answer: [letter]' on a new line."},
    {"role": "assistant", "content": "<reasoning> Let's think step by step.\n(1) The pears are more expensive than the kiwis: \"(cheap) ? ? kiwis ? pears ? ? (expensive)\".\n(2) The watermelons are less expensive than the peaches: \"(cheap) ? ? watermelons ? peaches ? ? (expensive)\".\n(3) The mangoes are the third-cheapest: \"(cheap) ? ? mangoes ? ? ? ?(expensive)\".\n(4) The watermelons are the third-most expensive: \"(cheap) ? ? ? ?  watermelons ? ? (expensive)\".\n(5) The plums are the second-most expensive: \"(cheap) ? ? ? ? ? plums ? (expensive)\".\n(6) The loquats are the second-cheapest: \"(cheap) ? loquats ? ? ? ? ? (expensive)\".\n(7) Combining (3), (4), (5), and (6) we get the following ordering: \"(cheap) ? loquats mangoes ? watermelons plums ? (expensive)\".\n(8) Combining (2) and (7) we get the following ordering: \"(cheap) ? loquats mangoes ? watermelons plums peaches (expensive)\".\n(9) Combining (1) and (8) we get the following ordering: \"(cheap) kiwis loquats mangoes pears watermelons plums peaches (expensive)\".\nAccording to this ordering, the third-most expensive fruit are watermelons.\nThe watermelons are the third-most expensive. </reasoning> <answer> Answer: C </answer>"}
]

AO_PROMPT = [
    {"role": "system", "content": "You are a logical deduction assistant."},
    {"role": "user", "content": "Q: The following paragraphs each describe a set of three objects arranged in a fixed order. The statements are logically consistent within each paragraph.\n\nIn a golf tournament, there were three golfers: Mel, Ada, and Ana. Mel finished last. Ana finished second.\nOptions:\nA) Mel finished second.\nB) Ada finished second.\nC) Ana finished second.\nProvide ONLY a single letter (A, B, C, etc.) as your answer without any explanation or additional text."},
    {"role": "assistant", "content": "A: C"},
    
    {"role": "user", "content": "Q: The following paragraphs each describe a set of five objects arranged in a fixed order. The statements are logically consistent within each paragraph.\n\nOn a shelf, there are five books: a green book, a blue book, a white book, a purple book, and a yellow book. The blue book is to the right of the yellow book. The white book is to the left of the yellow book. The blue book is the second from the right. The purple book is the second from the left.\nOptions:\nA) The green book is the second from the left.\nB) The blue book is the second from the left.\nC) The white book is the second from the left.\nD) The purple book is the second from the left.\nE) The yellow book is the second from the left.\nProvide ONLY a single letter (A, B, C, etc.) as your answer without any explanation or additional text."},
    {"role": "assistant", "content": "A: D"},
    
    {"role": "user", "content": "Q: The following paragraphs each describe a set of seven objects arranged in a fixed order. The statements are logically consistent within each paragraph.\n\nA fruit stand sells seven fruits: loquats, peaches, watermelons, plums, kiwis, mangoes, and pears. The pears are more expensive than the kiwis. The watermelons are less expensive than the peaches. The mangoes are the third-cheapest. The watermelons are the third-most expensive. The plums are the second-most expensive. The loquats are the second-cheapest.\nOptions:\nA) The loquats are the third-most expensive.\nB) The peaches are the third-most expensive.\nC) The watermelons are the third-most expensive.\nD) The plums are the third-most expensive.\nE) The kiwis are the third-most expensive.\nF) The mangoes are the third-most expensive.\nG) The pears are the third-most expensive.\nProvide ONLY a single letter (A, B, C, etc.) as your answer without any explanation or additional text."},
    {"role": "assistant", "content": "A: C"}
]



XML_COT_FORMAT = """\
<reasoning>
{reasoning}
</reasoning>
<answer>
{answer}
</answer>
"""